language: node_js
node_js:
  - stable
branches:
  only:
    - challenge3
install:
  - npm install
cache:
  directories:
    - node_modules
services: 
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage